version: "3.8"
services:
  app:
    build: ./docker/php
    container_name: Pigeon
    volumes:
      - ./src:/workspace

  web:
    image: nginx:1.21.6-alpine
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - ./src:/workspace
      - ./docker/nginx/pigeon.conf:/etc/nginx/conf.d/default.conf
    working_dir:
      /workspace
